<?php
$title = 'Add new Cmspage';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('success', array('action' => 'add')));
$form->prepare();
?>

<div class="border"> 
    <div class="padding"> 
    <div id="toolbar-box"> 
    <div class="t"> 
    <div class="t"> 
    <div class="t"></div> 
    </div> 
    </div> 
    <div class="m"> 
    <div class="toolbar" id="toolbar"> 
    
    <div class="clr"></div>
    </div> 
    <div class="header icon-48-article"> <h1><?php echo $this->escapeHtml($title); ?></h1>
    <p><?php  echo $this->error; ?></p></div> 
    <div class="clr"></div> 
    </div> 
    <div class="b"> 
    <div class="b"> 
    <div class="b"></div> 
    </div> 
    </div> 
    </div> 
    <div class="clr"></div>
    <div id="element-box">
    <div class="t"> 
    <div class="t"> 
    <div class="t"></div> 
    </div> 
    </div> 
    <div class="m">
<?php   echo $this->form()->openTag($form); ?>

    <?php  echo $this->formCollection($form); ?>
    <input id="input-save" type="submit" class="btn btn-warning" value="<?php echo $this->escapeHtml('Save'); ?>" name="submit">

 <?php    echo $this->form()->closeTag($form) ?>
    </div>
    <div class="cl"></div>
    <div class="b"> 
    <div class="b"> 
    <div class="b"></div> 
    </div> 
    </div>
    </div>
    </div>
    </div>
    </div>
     <script type="text/javascript">
                $( document ).ready( function() {
	$( 'textarea#editor1' ).ckeditor();
} );
                           </script>
    <script src="/ckeditor/ckeditor.js"></script>
<script src="/ckeditor/adapters/jquery.js"></script>