 <div class="border"> 
    <div class="padding"> 
    <div id="element-box"> 
    <div style=" width:700px; margin:auto; height:auto;">	
    <div id="cpanel">
		<div class="cl"></div>
    <div style="width:320px; float:left;">
    <div class="cl"></div>
    <div id="element-box">
    <h2 align="center" class="_in">Admin</h2>
    <div class="cl"></div>		
    <div class="t"  > 
	<div class="t" > 
		<div class="t" ></div> 
	</div> 
    </div> 
    <div class="m"> 
    <div class="icon"> 
    <a > 
    <img src="/images/header/icon-48-user.png" alt="Admin" />					<span>Admin</span></a> 
    </div> 
    <div class="home_in">
    
    
    <a href="<?php echo $this->url('success') ?>">Home</a>
    <a href="#">Change Password</a>
    <a href="<?php echo $this->url('auth', array('action' => 'logout')); ?>" id="link" onclick="return doConfirm(this.id);">Log Out</a>   
    
    </div>
    <div class="cl"></div>
    
    </div><!--end of m--->
    <div class="cl"></div> 	
    <div class="b"> 
    <div class="b"> 
	<div class="b"></div> 
    </div> 
    </div>	
    </div><!--end of element_box--->
    
    </div>
    
    
    <div style="width:285px; float:left; margin-left:50px; margin-bottom:20px;">
    <div class="cl"></div>
    <div id="element-box">
    <h2 align="center" class="_in">Manage Galley </h2>
    <div class="cl"></div>		
    <div class="t"  > 
	<div class="t" > 
		<div class="t" ></div> 
	</div> 
    </div> 
    <div class="m"> 
    <div class="icon"> 
    <a> 
    <img src="/images/header/icon-48-menumgr.png" alt="Manage Cms" />
    <span>Manage Galley</span></a> 
    </div>
    <div class="home_in">
    <a href="#">Add Galley</a>
    <a href="#">View Galley</a>
    <a href="#">Feature Galley</a>
    </div>
    <div class="cl"></div>
    
    </div><!--end of m--->
    <div class="cl"></div> 	
    <div class="b"> 
    <div class="b"> 
	<div class="b"></div> 
    </div> 
    </div>	
    </div><!--end of element_box--->
    
    </div>
    
    <div class="cl"></div>
    
    <div style="width:320px; float:left;">
    <div class="cl"></div>
    <div id="element-box">
    <h2 align="center" class="_in"> Manage User</h2>
    <div class="cl"></div>		
    <div class="t"  > 
	<div class="t" > 
		<div class="t" ></div> 
	</div> 
    </div> 
    <div class="m"> 
    <div class="icon"> 
    <a > 
    <img src="/images/header/icon-48-frontpage.png" alt="Home Owner" />					<span> Manage Agent</span></a> 
    </div> 
    <div class="home_in">
    <a href="#">Add Usert</a>
    <a href="#">View User</a>
  
    </div>
    <div class="cl"></div>
    
    </div><!--end of m--->
    <div class="cl"></div> 	
    <div class="b"> 
    <div class="b"> 
	<div class="b"></div> 
    </div> 
    </div>	
    </div><!--end of element_box--->
    
    </div>
    <div style="width:285px; float:left;margin-left:50px;">
    <div class="cl"></div>
    <div id="element-box">
    <h2 align="center" class="_in">Manage Events</h2>
    <div class="cl"></div>		
    <div class="t"  > 
	<div class="t" > 
		<div class="t" ></div> 
	</div> 
    </div> 
    <div class="m"> 
    <div class="icon"> 
    <a > 
    <img src="/images/header/icon-48-frontpage.png" alt="Home Owner" /><span>Manage Events</span></a> 
    </div> 
    <div class="home_in">
    <a href="#">add Events</a>
    <a href="#">View Events</a>
    </div>
    <div class="cl"></div>
    
    </div><!--end of m--->
    <div class="cl"></div> 	
    <div class="b"> 
    <div class="b"> 
	<div class="b"></div> 
    </div> 
    </div>	
    </div><!--end of element_box--->
    
    </div>
    
    <div class="cl"></div>
    </div><!--end of cpanel--->
    <div class="cl"></div>
    </div><!--end of div--->
    <div class="cl"></div>
    </div> 
    <div class="clr"></div> 
    </div> 
    </div> 