    <div class="border"> 
    <div class="padding"> 
    <div id="toolbar-box"> 
    <div class="t"> 
    <div class="t"> 
    <div class="t"></div> 
    </div> 
    </div> 
    <div class="m"> 
    <div class="toolbar" id="toolbar"> 
    
    <div class="clr"></div>
    </div> 
    <div class="header icon-48-article">Change Password</div> 
    <div class="clr"></div> 
    </div> 
    <div class="b"> 
    <div class="b"> 
    <div class="b"></div> 
    </div> 
    </div> 
    </div> 
    <div class="clr"></div>
    <div id="element-box">
    <div style="width:350px; height:auto; margin:auto;">
    <div class="t"> 
    <div class="t"> 
    <div class="t"></div> 
    </div> 
    </div> 
    <div class="m">
        
        
<?php 
$form = $this->form;
$form->setAttribute('action',$this->url('auth', array('action' => 'change-password')));
$form->setAttribute('id','changepassform');
$form->setAttribute('enctype','multipart/form-data');
$form->prepare();

echo $this->form()->openTag($form);
?>
 <table border="0" cellpadding="5" cellspacing="0" align="center" class="reg_table" >
   <tr><td>&nbsp;</td></tr>
   
	<tr>
      <td width="150"><strong><?php echo $this->formLabel($this->form->get('oldpassword')); ?></strong></td>
      <td width="215">  <?php echo $this->formElement($this->form->get('oldpassword')); ?>
           <?php echo $this->formElementErrors($this->form->get('oldpassword'), array('class' => 'text-danger')); ?>
        </td>
    </tr>
    <tr>
      <td width="150"><strong> <?php echo $this->formLabel($this->form->get('password')); ?></strong></td>
      <td width="215">   <?php echo $this->formElement($this->form->get('password')); ?>
            <?php echo $this->formElementErrors($this->form->get('password'), array('class' => 'text-danger')); ?>
      </td>
    </tr>
    <tr>
      <td><strong><?php echo $this->formLabel($this->form->get('password_confirm')); ?></strong></td>
      <td>  <?php echo $this->formElement($this->form->get('password_confirm')); ?>
            <?php echo $this->formElementErrors($this->form->get('password_confirm'), array('class' => 'text-danger')); ?>
        </td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td colspan="2"><label>
       <?php echo $this->formElement($this->form->get('Loginsubmit')); ?> </td>
    </tr>
  </table>
<?php 

echo $this->form()->closeTag();

?>
        
</div>
	<div class="cl"></div>
	<div class="b"> 
				<div class="b"> 
		 			<div class="b"></div> 
				</div> 
			</div>
  </div>
</div>
</div>
</div>
