<?php 
$title = 'Show list of user';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table clickable table-striped table-hover">
    <colgroup>
        <col width="20%">
        <col width="20%">
        <col width="20%">
        <col width="20%">
        <col width="10%">
        <col width="5%">
        <col width="5%">
    </colgroup>
    <thead>
        <tr>
            <th><?php echo $this->escapeHtml('Lastname'); ?></th>
            <th><?php echo $this->escapeHtml('Firstname'); ?></th>
            <th><?php echo $this->escapeHtml('Email'); ?></th>
            <th><?php echo $this->escapeHtml('Login'); ?></th>
            <th><?php echo $this->escapeHtml('Is active'); ?></th>
            <th class="text-center"><?php echo $this->escapeHtml('Edit'); ?></th>
            <th class="text-center"><?php echo $this->escapeHtml('Delete'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->users as $user):
        
      // echo '<pre>'; var_dump($user); die;?>
            <tr>
                <td><?php echo $this->escapeHtml($user['lname']); ?></td>
                <td><?php echo $this->escapeHtml($user['fname']); ?></td>
                <td><?php echo $this->escapeHtml($user['email']); ?></td>
                <td><?php echo $this->escapeHtml($user['username']); ?></td>
                <td><?php echo $this->escapeHtml($user['active']? 'Yes' : 'No'); ?></td>
                <td class="text-center">
                    <a href="<?php echo $this->url('auth',  array('action' => 'edit','id' => $user['id'])); ?>" class="edit-line">
                        <img src="/backend/images/icones/edit.png" alt="<?php echo $this->escapeHtml('Edit'); ?>" />
                    </a>
                </td>
                <td class="text-center">
                    <a href="<?php echo $this->url('auth',  array('action' => 'delete','id' =>$user['id'])); ?>" class="delete-line">
                        <img src="<?php echo '/backend/images/icones/delete.png'; ?>" alt="<?php echo $this->escapeHtml('Delete'); ?>">
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

