<?php echo $this->doctype();
$user=$_SESSION['admin'];

?>
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    
    <meta charset="utf-8">
    <?php echo $this->headTitle('Chaudharyweb.com '. $this->translate('ZF2 Login'))->setSeparator(' - ')->setAutoEscape(false) ?>
    
  <?php echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    
    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    ->prependStylesheet($this->basePath() . '/css/stylelogin.css')
     ->prependStylesheet($this->basePath() . '/css/bootstrap.css');?>
    
    
    <!-- Scripts -->
    <?php echo $this->headScript()
    ->prependFile($this->basePath() . '/js/jquery.min.js')
    ->prependFile($this->basePath() . '/js/dropdown_menu.js');
    ; ?>
    </head>
    <body>
    
    
    <div class="header_top">
    <a href="<?php echo $this->url('success') ?>"><span class="title">Welcome To Chaudharyweb.com</span> </a>
    
    
    <div  class="top_right"><span style="margin-right: 66px;"><?php  echo $user->name; ?></span><a href="<?php echo $this->url('auth', array('action' => 'logout')); ?>">Logout</a></div>
    
    </div>
    <div class="chromestyle" id="chromemenu">
    
    <ul>
    
    
    <li><a href="#" rel="dropmenu1">Admin </a></li>
    <li><a href="#"  rel="dropmenu2"> Manage User</a></li>
     <li><a href="#"  rel="dropmenu3">Cms page</a></li>
    
    
    
    </ul>
    </div>
    <div id="dropmenu1" class="dropmenudiv" style="width:150px;">
    <a href="<?php echo $this->url('success') ?>">Home</a>
    <a href="<?php echo $this->url('auth', array('action' => 'change-password')); ?>">Change Password</a>
    <a href="<?php echo $this->url('auth', array('action' => 'logout')); ?>" id="link" onclick="return doConfirm(this.id);">Log Out</a>                                 
    </div>
    
    <div id="dropmenu3" class="dropmenudiv">		
    <a href="<?php echo $this->url('success', array('action' => 'cmspage')); ?>">View  Pages</a>
    <a href="<?php echo $this->url('success', array('action' => 'add')); ?>">Add  Pages</a>								                
    </div>		
       
    <div id="dropmenu2" class="dropmenudiv" style="width:220px;">		
    <a href="<?php echo $this->url('auth', array('action' => 'user')); ?>">Register user</a>
    <a href="<?php echo $this->url('auth', array('action' => 'add')); ?>">Add User</a>
    </div>
    
    
    
    
    
    
    <script type="text/javascript">
    
    cssdropdown.startchrome("chromemenu")
    
    </script>
    <div id="content-box">
       <?php echo $this->partial('messages.phtml', array('messages' => $this->flashMessages)); ?>
     <?php echo $this->content; ?>
    </div> 
    <div id="border-bottom"><div>
    </div>
    
    <div class="foot">Copyright &copy; chaudharyweb.com</div>
    
    </body>
    </html>