<?php echo $this->doctype(); ?>
    
    <html lang="en">
    <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Chaudharyweb.com '. $this->translate('ZF2 Login'))->setSeparator(' - ')->setAutoEscape(false) ?>
    
    <?php echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    
    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    ->prependStylesheet($this->basePath() . '/css/stylelogin.css')
    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
    
    
    <!-- Scripts -->
    <?php echo $this->headScript()
    ->prependFile($this->basePath() . '/js/jquery.min.js');
    ; ?>
    
    </head>
    <body>
    
    <div class="header_top">
    <a href="<?php echo $this->url('home') ?>">
    <span class="title">Chaudharyweb.com admin </span> </a></div>
    
    <div id="content-box"> 
    <div class="padding"> 
    <div id="element-box" class="login"  style="padding-top:30px;"> 
    <h2 align="center";>Administrator Login</h2>
    <div class="t"> 
    <div class="t"> 
    <div class="t"></div> 
    </div> 
    </div> 
    <div class="m"> 
    
    <div id="section-box" style="margin-top:10px;"> 
    <div class="t"> 
    <div class="t"> 
    <div class="t"></div> 
    </div> 
    </div> 
    <div class="m">            <?php echo $this->content; ?>
    <div class="clr"></div> 
    </div> 
    
    <div class="b"> 
    <div class="b"> 
    <div class="b"></div> 
    </div> 
    </div> 
    </div> 
    
    <div id="lock"></div> 
    <div class="clr"></div> 
    </div> 
    <div class="b"> 
    <div class="b"> 
    <div class="b"></div> 
    </div> 
    </div> 
    </div> 
    
    <div class="clr"></div> 
    </div> 
    </div> 
    <div id="border-bottom"><div><div></div></div> 
    </div> <div class="foot">Copyright &copy; chaudharyweb.com</div>

    </body>
    </html>