<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sZend Framework 2%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zf2" target="_blank"><?php echo $this->translate('Fork Zend Framework 2 on GitHub') ?> &raquo;</a></p>
</div>

<div class="row">

   <?php
$title = 'Add new about us';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('application', array('action' => 'aboutus')));
$form->prepare();

echo $this->form()->openTag($form) . '<br/>';
echo $this->formHidden($form->get('id')) .  '<br/>';
echo $this->formRow($form->get('fname')) .  '<br/>';
echo $this->formRow($form->get('lname')) .  '<br/>';
echo $this->formRow($form->get('email')) .  '<br/>';
echo $this->formRow($form->get('password')) .  '<br/>';
echo $this->formInput($form->get('submit')) .  '<br/>';
echo $this->form()->closeTag($form) .  '<br/>';
?>

</div>
